### PR TITLE
countdown ready

### PR DESCRIPTION
**Pull request by aaavvvooo**

### CODE REVIEW

**Comment by Artash00** [comment]
Great code, everything works correctly, only here it is written in the example
let's say 00:05:08, and you have 0:5:8, that is, you forgot to add 0.
but overall everything else is ok, good job!

**Comment by aaavvvooo** [comment]
Thanks for your observation, I'll fix it

**Comment by ArshTumo** [comment]
Program crashes when I input letters instead of numbers. Exceptions need to be raised to fix that.

**Comment by aaavvvooo** [comment]
Can you provide a test case, when you recieved crash?
Because I tested f.e. a:b:c, 1a:2:3, www:ee:rrr and so on, and the program does not crash, it prints "Wrong input" and exits

**Comment by ArshTumo** [comment]
Sorry, github tricked me. I was not reviewing the full code. It really works fine.

**Pull request merged**
